[SC-231] Build basic sparklend cap automator
marsfoundation/sparklend-cap-automator pull request #1
Opened 2023-11-17 10:30 UTC by barrutko

2023-11-30 13:24 UTC, hexonaut requested changes
Looked over general structure. Direction looks good. I'll do a full review after the requested changes.

2023-11-30 13:24 UTC, hexonaut commented on src/CapAutomator.sol
> +        require(capIncreaseCooldown <= 2**48 - 1, "CapAutomator/invalid-cooldown");
Use `type(uint48).max`.

2023-11-30 13:24 UTC, hexonaut commented on src/CapAutomator.sol
> +    address public override authority;
I want to move away from rolling our own auth and just start using the openzeppelin libraries for this. This contract is simple enough that owner version should be fine: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol

If this were to require more complex setup then let's start preferring https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol .

2023-11-30 13:24 UTC, hexonaut commented on src/CapAutomator.sol
> +        (,uint256 currentSupplyCap) = dataProvider.getReserveCaps(asset);
The `dataProvider` can be changed, so I would avoid using it and prefer lower-level access for something like this. The `getReserveData()` returns all this data and you can use `using ReserveConfiguration for DataTypes.ReserveConfigurationMap` to parse the configuration from the `uint256` easily enough.

2023-11-30 13:24 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint48  lastIncreaseTime;    // seconds
I think these names can be made more concise by removing the word "cap" from each as this is the "cap config" struct. `max`, `gap`, `increaseCooldown`.

2023-12-06 12:55 UTC, hexonaut requested changes

2023-12-06 12:55 UTC, hexonaut commented on src/CapAutomator.sol
> +}
You should use the interfaces in `aave-v3-core` library.

2023-12-06 12:55 UTC, hexonaut commented on src/CapAutomator.sol
> +}
You can use `erc20-helpers` library for this interface: https://github.com/marsfoundation/erc20-helpers/blob/master/src/interfaces/IERC20.sol . That's what it's there for.

2023-12-06 12:55 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 gap;
These are restricted to whole units in the `ReserveConfigurationMap` so we can limit these to 36 bits each to pack this whole config into one storage slot. You should also mark the units of these to be "whole units".

2023-12-06 12:55 UTC, hexonaut commented on src/CapAutomator.sol
> +    address public override immutable pool;
I would type these with the official interfaces once imported from `aave-v3-core` and update the `ICapAutomator` to match.

2023-12-06 12:55 UTC, hexonaut commented on src/CapAutomator.sol
> +    constructor(address _poolConfigurator, address _pool) Ownable(msg.sender) {
It might be easier to just import both of these from the `PoolAddressesProvider` and only pass that single address in as constructor arg. This reduces the amount needing to be specified and guarantees that both addresses are linked at deploy time.

IE `poolAddressesProvider.getPool()` and `poolAddressesProvider.getPoolConfigurator()`

2023-12-06 13:30 UTC, hexonaut requested changes

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +            uint48(increaseCooldown),
I would include a comment saying this cast was checked in the `_validateCapConfig`.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +            supplyCapConfigs[asset].lastIncreaseTime
Not a huge deal since this is infrequently called, but I would cache the SLOAD into memory to prevent two SLOADs on the same storage slot.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +            uint48(increaseCooldown),
Same about comment.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +            borrowCapConfigs[asset].lastIncreaseTime
Same about SLOAD caching.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 currentSupply    = ERC20Like(reserveData.aTokenAddress).totalSupply();
This is not quite right. It needs to match the formula used in `ValidationLogic.validateSupply()` which includes the treasury accrual.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +            supplyCapConfigs[asset].lastUpdateBlock  = uint48(block.number);
This should be reduced to one SSTORE. I would just set the whole storage slot after the change to make it all fit in one word. I realize the autoline for Maker relies on the Optimizer to do this, but I don't like doing that if we can make the struct 1 word.

In fact it's probably best to load the cap config into a memory slot in the top of the function and just update the memory slot and finally write it out to storage at the end.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +        }
Same here with storage optimization.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint48 lastIncreaseTime    = capConfig.lastIncreaseTime;
I would drop loading these into local variables as they are each read only once.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 gap = capConfig.gap;
Same here. This is only used once, so inline it.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 currentSupply    = ERC20Like(reserveData.aTokenAddress).totalSupply();
I would just put everything into whole units right away, so `uint256 currentSupply    = ERC20Like(reserveData.aTokenAddress).totalSupply() / ERC20Like(reserveData.aTokenAddress).decimals();`. Then you don't need to pass along decimals into the new cap calculations.

2023-12-06 13:30 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 currentBorrow    = ERC20Like(reserveData.variableDebtTokenAddress).totalSupply();
Same here would divide by decimals into whole units.

2023-12-07 12:00 UTC, hexonaut requested changes

2023-12-07 12:00 UTC, hexonaut commented on src/CapAutomator.sol
> +import { ERC20 } from "openzeppelin-contracts/token/ERC20/ERC20.sol";
Alignment.

2023-12-07 12:00 UTC, hexonaut commented on src/CapAutomator.sol
> +        // casting from uint256 to uin48 validated in _validateCapConfig
Typo `uint48`.

2023-12-07 12:00 UTC, hexonaut commented on src/CapAutomator.sol
> +        require(gap <= type(uint48).max,              "CapAutomator/invalid-gap");
I would constrain `max` by `ReserveConfiguration.MAX_VALID_SUPPLY_CAP` (and similar for borrow), and `gap` should be less than or equal to the `max`.

2023-12-07 12:00 UTC, hexonaut commented on src/CapAutomator.sol
> +        // casting from uint256 to uin48 validated in _validateCapConfig
Same typo `uint48`.

2023-12-07 12:02 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 currentSupply    = ERC20Like(reserveData.aTokenAddress).totalSupply();
This should match the formula for supply cap checking exactly.

`(ERC20(reserveData.aTokenAddress).scaledTotalSupply() + reserveData.accruedToTreasury).rayMul(reserveData.liquidityIndex)`

2023-12-07 12:20 UTC, hexonaut requested changes

2023-12-07 12:20 UTC, hexonaut commented on src/CapAutomator.sol
>          if(max == 0) return currentCap;
Inconsistent spacing after the `if`. Usually there is one space after the `if`.

2023-12-08 13:20 UTC, hexonaut requested changes

2023-12-08 13:20 UTC, hexonaut commented on src/CapAutomator.sol
> +        uint256 currentSupply    = (IScaledBalanceToken(reserveData.aTokenAddress).scaledTotalSupply() + uint256(reserveData.liquidityIndex).rayMul(reserveData.accruedToTreasury))
This formula is now completely incorrect. It needs to be `(ERC20(reserveData.aTokenAddress).scaledTotalSupply() + reserveData.accruedToTreasury).rayMul(reserveData.liquidityIndex)`.

2023-12-08 13:20 UTC, hexonaut commented on src/CapAutomator.sol
>          uint256 currentBorrow    = ERC20(reserveData.variableDebtTokenAddress).totalSupply() / 10 ** ERC20(reserveData.variableDebtTokenAddress).decimals();
Maybe include a comment that we do not use stable borrow feature.

2023-12-08 13:20 UTC, hexonaut commented on test/CapAutomator.t.sol
> +import { IPoolConfigurator }    from 'aave-v3-core/contracts/interfaces/IPoolConfigurator.sol';
Should be double quotes `"` instead of single `'`.

2023-12-08 14:49 UTC, hexonaut requested changes

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
There should be two separate contracts for `PoolMock` and `PoolConfiguratorMock`. I understand the shortcut, but it's important to test the actual different address incase you accidentally placed a pool call instead of a poolConfigurator in some place in the code.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            1_000,
This would actually fail for invalid `gap` as well. I would set it to 0.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +
Extra newline.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            uint256 gap,
These should be `uint48` now.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            uint256 gap,
`uint48`

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            uint256 gap,
`uint48`

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            uint256 gap,
`uint48`

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        assertNotEq(postExecIncreaseTime, 0);
Why asserting these are not eq instead of equal to the new values?

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            uint256 gap,
`uint48`

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +            uint256 gap,
`uint48`

2023-12-08 14:49 UTC, hexonaut commented on src/interfaces/ICapAutomator.sol
> +     *  @param asset The address of the asset for which supply borrow was removed
Typo should be `borrow config` instead of `supply borrow`.

2023-12-08 14:49 UTC, hexonaut commented on src/CapAutomator.sol
> +    ) external onlyOwner {
Add `override`.

2023-12-08 14:49 UTC, hexonaut commented on src/CapAutomator.sol
> +    ) external onlyOwner {
Add `override`.

2023-12-08 14:49 UTC, hexonaut commented on src/CapAutomator.sol
> +    function removeSupplyCapConfig(address asset) external onlyOwner {
Add `override`.

2023-12-08 14:49 UTC, hexonaut commented on src/CapAutomator.sol
> +    function removeBorrowCapConfig(address asset) external onlyOwner {
Add `override`.

2023-12-08 14:49 UTC, hexonaut commented on src/CapAutomator.sol
> +    function exec(address asset) external returns (uint256 newSupplyCap, uint256 newBorrowCap){
Add `override`.

2023-12-08 14:49 UTC, hexonaut commented on src/CapAutomator.sol
> +        newBorrowCap = _updateBorrowCapConfig(asset);
I think we should allow for updating only one of these at a time. An additional external function called `execSupply` / `execBorrow` could work.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        capAutomator = new CapAutomatorHarness(address(mockPoolAddressesProvider));
Missing transfer ownership?

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
Split out to separate contracts pool + poolConfigurator same as above.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
Same split out contracts.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
Same split out contracts.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        mockPool.setBorrowCap(4_000);
Why is this all being set? It looks like the only place it's being used is in the `_updateSupplyCapConfig` tests and you are not inheriting from this base contract there.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        // aToken.totalSupply + accruedToTreasury * liquidityIndex = 6_900
Needs to be fixed based on our chat. Also the atoken supply / treasury should be in 18 decimal units.

2023-12-08 14:49 UTC, hexonaut commented on test/mocks/MockPool.sol
> +        debtToken = new MockToken();
These should be 18 decimals.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        mockPool.setATokenScaledTotalSupply(6_900 * 10**6);
Treasury value should also use 6 decimals here.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator._updateSupplyCapConfigExternal(asset), 7_000);
Why does this call the `setSupplyCap()` if there is no change? Line 167 seems to short circuit this and just return the current supply cap.

2023-12-08 14:49 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator._updateBorrowCapConfigExternal(asset), 4_000);
Same here. Why is this calling `setBorrowCap()` with no change?

2023-12-08 16:22 UTC, barrutko commented on test/CapAutomator.t.sol
> +        capAutomator = new CapAutomatorHarness(address(mockPoolAddressesProvider));
Removed it, it's not needed in this test suite. I can add it back though.

2023-12-08 16:59 UTC, barrutko commented on test/CapAutomator.t.sol
> +        mockPool.setBorrowCap(4_000);
Now they actually are inheriting from it, plus changed the setup to 18 decimals

2023-12-08 17:05 UTC, barrutko commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator._updateSupplyCapConfigExternal(asset), 7_000);
The last arg of `vm.expectCall` is the expected call count. Here it is set to 0.
You are exactly right that the calculations are returning the same cap and her I'm testing that when calculations returned the same cap for whatever reason, the automator is not going to call the poolConfigurator unnecessarily.

2023-12-08 17:06 UTC, barrutko commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator._updateBorrowCapConfigExternal(asset), 4_000);
Same as above.

2023-12-08 17:10 UTC, hexonaut commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator._updateSupplyCapConfigExternal(asset), 7_000);
ahh missed that

2023-12-08 17:19 UTC, hexonaut requested changes

2023-12-08 17:19 UTC, hexonaut commented on src/CapAutomator.sol
> +    function exec(address asset) external override returns (uint256 newSupplyCap, uint256 newBorrowCap){
Consistency on space before opening brace `{`.

2023-12-08 17:19 UTC, hexonaut commented on src/CapAutomator.sol
> +    function execSupply(address asset) external override returns (uint256){
Consistency on space before opening brace `{`.

2023-12-08 17:19 UTC, hexonaut commented on src/CapAutomator.sol
> +    function execBorrow(address asset) external override returns (uint256){
Consistency on space before opening brace `{`.

2023-12-11 16:23 UTC, hexonaut requested changes
Just one more thing and good to merge.

2023-12-11 16:23 UTC, hexonaut commented on test/CapAutomator.t.sol
>          mockPool.debtToken().setDecimals(18);
These are not different decimals. :)

2023-12-11 17:34 UTC, lucas-manuel requested changes

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        uint256 currentSupply    = (IScaledBalanceToken(reserveData.aTokenAddress).scaledTotalSupply() + uint256(reserveData.accruedToTreasury)).rayMul(reserveData.liquidityIndex)
Lets multiline this to make the line length shorter

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +
```suggestion
import { ReserveConfiguration }
    from "aave-v3-core/contracts/protocol/libraries/configuration/ReserveConfiguration.sol";

import { DataTypes } from "aave-v3-core/contracts/protocol/libraries/types/DataTypes.sol";
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +        configuration.setBorrowCap(borrowCap);
```suggestion
        DataTypes.ReserveConfigurationMap memory configuration 
            = DataTypes.ReserveConfigurationMap(0);
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +        });
```suggestion
        return DataTypes.ReserveData({
            configuration:               configuration,
            liquidityIndex:              uint128(liquidityIndex),
            currentLiquidityRate:        uint128(0),
            variableBorrowIndex:         uint128(0),
            currentVariableBorrowRate:   uint128(0),
            currentStableBorrowRate:     uint128(0),
            lastUpdateTimestamp:         uint40(0),
            id:                          uint16(0),
            aTokenAddress:               address(aToken),
            stableDebtTokenAddress:      address(0),
            variableDebtTokenAddress:    address(debtToken),
            interestRateStrategyAddress: address(0),
            accruedToTreasury:           uint128(accruedToTreasury),
            unbacked:                    uint128(0),
            isolationModeTotalDebt:      uint128(0)
        });
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +    /*** Pool functions                                                                         ***/
Functions

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +    /**********************************************************************************************/
Functions

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +    /*** Mock functions                                                                         ***/
Functions

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +    }
Duplicated functions

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPoolAddressesProvider.sol
> +    address public pool;
New line at beginning of contract

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockPoolAddressesProvider.sol
> +    }
New line at end of contract

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockToken.sol
> +    uint256 public totalSupply;
New line at beginning

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockToken.sol
> +    }
New line at end

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
        mockPoolAddressesProvider = new MockPoolAddressesProvider(makeAddr("pool"), makeAddr("poolConfigurator"));
        capAutomator              = new CapAutomator(address(mockPoolAddressesProvider));
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
        mockPool                  = new MockPool();
        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    }
```suggestion
        assertEq(address(capAutomator.pool()),             makeAddr("pool"));
        assertEq(address(capAutomator.poolConfigurator()), makeAddr("poolConfigurator"));
        assertEq(address(capAutomator.owner()),            address(this));
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
Rm extra line

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
Rm new line

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.roll(100);
```suggestion
        mockPool                  = new MockPool();
        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.roll(100);
Put this comment above

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        assertEq(lastUpdateBlockAfter,  100);
```suggestion
        ( ,,,uint48 lastUpdateBlockAfter, uint48 lastIncreaseTimeAfter ) = capAutomator.supplyCapConfigs(asset);
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        assertEq(lastUpdateBlockAfter,  100);
Applies to all

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.roll(100);
```suggestion
        mockPool                  = new MockPool();
        mockPoolAddressesProvider = new MockPoolAddressesProvider(address(mockPool), address(mockPool));
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
`10 ** 18`

2023-12-11 17:34 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
        ( uint256 newSupplyCap, uint256 newBorrowCap ) = capAutomator.exec(asset);
```

2023-12-11 17:34 UTC, lucas-manuel commented on test/harnesses/CapAutomatorHarness.sol
> +
```suggestion
    constructor(address poolAddressesProvider) CapAutomator(poolAddressesProvider) {}
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     *  @param increaseCooldown A mimimum period of time that needs to elapse between consequent cap increases
`mimimum => minimum` everywhere in file

2023-12-11 17:34 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     */
Apply this formatting to all sections, add periods everywhere

2023-12-11 17:34 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     */
```suggestion
    /**
     *  @dev   Event to log the setting of a new supply cap config.
     *  @param asset            The address of the asset for which the config was set.
     *  @param max              Maximum allowed supply cap.
     *  @param gap              A gap between the supply and the supply cap that is being maintained.
     *  @param increaseCooldown A mimimum period of time that needs to elapse between consequent cap increases.
     */
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     *  @param asset The address
`The address of the asset.`, add everywhere applicable

2023-12-11 17:34 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     */
This is the formatting with @return included
```suggestion
    /**
     *  @dev    Returns current configuration for automatic supply cap management
     *  @param  asset            The address of the asset which config is going to be returned.
     *  @return max              Maximum allowed supply cap.
     *  @return gap              A gap between the supply and the supply cap that is being maintained.
     *  @return increaseCooldown A mimimum period of time that needs to elapse between consequent cap increases.
     *  @return lastUpdateBlock  The block of the last cap update.
     *  @return lastIncreaseTime The timestamp of the last cap increase.
     */
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     */
```suggestion
    /**
     *  @dev    A public function that updates supply and borrow caps on markets of a given asset.
     *          The supply and borrow caps are going to be set to, respectively, the values equal
     *          to the sum of current supply and the supply cap gap and the the sum of current
     *          borrows and the borrow cap gap. The caps are only going to be increased if the
     *          required cooldown time has passed. Calling this function more than once per
     *          block will not have any additional effect.
     *  @param  asset        The address of the asset which caps are going to be updated
     *  @return newSupplyCap A newly set supply cap, or the old one if it was not updated
     *  @return newBorrowCap A newly set borrow cap, or the old one if it was not updated
     */
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +
I think 120 line length is good for this file, this would be the section header length
```suggestion
    /******************************************************************************************************************/
    /*** Declarations and Constructor                                                                               ***/
    /******************************************************************************************************************/
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        uint48 max;              // full tokens
Sentence case for all comments (`Full tokens`)

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +    }
Lets add safe casting:

```solidity
    function _uint48(uint256 input_) internal pure returns (uint48 output_) {
        require(input_ <= type(uint48).max, "CapAutomator/uint48-cast");
        output_ = uint48(input_);
    }
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +            uint48(max),
Use safe casting function for all casting

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        require(increaseCooldown <= type(uint48).max,             "CapAutomator/invalid-cooldown");
No longer need this with safe casting function

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        require(increaseCooldown <= type(uint48).max,             "CapAutomator/invalid-cooldown");
Don't need with safe cast

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +    }
```suggestion
    function exec(address asset) external returns (uint256 newSupplyCap, uint256 newBorrowCap) {
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +
```suggestion
        if (max == 0 || capConfig.lastUpdateBlock == block.number) return currentCap;
```

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        uint256 currentState,
Nit but I think `currentValue` makes more intuitive sense than `currentState`, makes it more obvious that its about the value that we're capping

2023-12-11 17:34 UTC, lucas-manuel commented on test/mocks/MockToken.sol
> +    }
Use double underscores for all explicit mock setters like this. `__setDecimals`

2023-12-11 17:34 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        uint256 currentSupplyCap = reserveData.configuration.getSupplyCap();
```suggestion
        uint256 scaledSupply =
            IScaledBalanceToken(reserveData.aTokenAddress).scaledTotalSupply() + uint256(reserveData.accruedToTreasury);

        uint256 currentSupply =
            scaledSupply.rayMul(reserveData.liquidityIndex) / 10 ** ERC20(reserveData.aTokenAddress).decimals();

        uint256 currentSupplyCap = reserveData.configuration.getSupplyCap();
```

2023-12-11 17:37 UTC, lucas-manuel requested changes

2023-12-11 17:37 UTC, lucas-manuel commented on src/CapAutomator.sol
> +
```suggestion
        ERC20 aToken = ERC20(reserveData.aTokenAddress);
        uint256 currentBorrow = aToken.totalSupply() / 10 ** aToken.decimals();
```

2023-12-12 10:33 UTC, barrutko commented on src/CapAutomator.sol
> +
You mean `variableDebtTokenAddress `, not `aToken`, right?

2023-12-12 10:44 UTC, barrutko commented on test/CapAutomator.t.sol
> +
Are you sure it's not ok with this one line gap?

2023-12-12 10:53 UTC, barrutko commented on test/CapAutomator.t.sol
> +        vm.roll(100);
Not sure what do you mean here. These mock contracts are deployed in `CapAutomatorUnitTestBase `

2023-12-12 10:54 UTC, barrutko commented on test/CapAutomator.t.sol
> +        vm.roll(100);
Not sure what do you mean here. These mock contracts are deployed in `CapAutomatorUnitTestBase `

2023-12-12 10:54 UTC, barrutko commented on test/CapAutomator.t.sol
> +        vm.roll(100);
What comment?

2023-12-12 10:55 UTC, barrutko commented on test/CapAutomator.t.sol
> +        assertEq(lastUpdateBlockAfter,  100);
Not sure what do you mean here

2023-12-12 10:57 UTC, barrutko commented on test/CapAutomator.t.sol
> +
Not sure what do you mean here

2023-12-12 10:59 UTC, barrutko commented on test/CapAutomator.t.sol
> +        assertEq(lastUpdateBlockAfter,  100);
Ah, ok. You just commented the wrong line. Extra spaces, now I see.

2023-12-12 11:05 UTC, barrutko commented on test/mocks/MockPool.sol
> +
I'm not so sure about this multiline imports splitting, even if these lines are pretty long. Do you have a strong opinion here?

2023-12-12 11:06 UTC, barrutko commented on test/mocks/MockPool.sol
> +        configuration.setBorrowCap(borrowCap);
Please make sure to comment the right line - it can be a little confusing 😁

2023-12-12 11:09 UTC, barrutko commented on test/mocks/MockPool.sol
> +    }
Are they...? They set the internal state of the mock and are used by the mock pool configurator.

2023-12-12 13:32 UTC, hexonaut commented on src/CapAutomator.sol
> +
This change actually requires more gas (maybe the optimizer cancels it out?), so I would say leave it as-is. In general you don't want to allocate a new stack slot for an interface typecast as it doesn't do anything at the runtime level.

2023-12-12 13:51 UTC, hexonaut commented on src/CapAutomator.sol
> +            uint48(max),
No need as it is constrained by the `MAX_VALID_SUPPLY_CAP` and `gap` is constrained by `max`. Only the `increaseCooldown` needs to use the safe cast. We should be somewhat gas-consciencious here.

2023-12-12 18:08 UTC, hexonaut submitted a review, later dismissed
Latest changes LGTM. Ready to merge.

2023-12-12 22:11 UTC, lucas-manuel requested changes

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
import { CapAutomatorHarness } from "./harnesses/CapAutomatorHarness.sol";
```

2023-12-12 22:11 UTC, lucas-manuel commented on test/mocks/MockPool.sol
> +        });
```suggestion
        return DataTypes.ReserveData({
            configuration:               configuration,
            liquidityIndex:              uint128(liquidityIndex),
            currentLiquidityRate:        uint128(0),
            variableBorrowIndex:         uint128(0),
            currentVariableBorrowRate:   uint128(0),
            currentStableBorrowRate:     uint128(0),
            lastUpdateTimestamp:         uint40(0),
            id:                          uint16(0),
            aTokenAddress:               address(aToken),
            stableDebtTokenAddress:      address(0),
            variableDebtTokenAddress:    address(debtToken),
            interestRateStrategyAddress: address(0),
            accruedToTreasury:           uint128(accruedToTreasury),
            unbacked:                    uint128(0),
            isolationModeTotalDebt:      uint128(0)
        });
```

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        // (aToken.totalSupply + accruedToTreasury) * liquidityIndex = 6_900e18
`aToken.scaledTotalSupply`

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.prank(makeAddr("notOwner"));
Should be in RenounceOwnershipTestsa contract

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.prank(owner);
Should have `owner` assertion before

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    function test_setSupplyCapConfig_invalidCooldown() public {
Order all reversion tests in the order that they occur:

```
        require(max > 0,                                          "CapAutomator/invalid-cap");
        require(max <= ReserveConfiguration.MAX_VALID_SUPPLY_CAP, "CapAutomator/invalid-cap");
        require(gap <= max,                                       "CapAutomator/invalid-gap");
```

2023-12-12 22:11 UTC, lucas-manuel commented on src/CapAutomator.sol
> +        require(max <= ReserveConfiguration.MAX_VALID_SUPPLY_CAP, "CapAutomator/invalid-cap");
Two `invalid-cap` errors, we should change one of these

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    function test_setSupplyCapConfig_invalidCap() public {
Should be split into two tests once we have different error messages

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    function test_setSupplyCapConfig_invalidCooldown() public {
Also for all failure mode tests that occur at specific values (applies to all three of these) there should be a corresponding successful call to demonstrate that the value provided actually was at the boundary condition.

E.g., 

```
max == ReserveConfiguration.MAX_VALID_SUPPLY_CAP + 1 (fail)
max == ReserveConfiguration.MAX_VALID_SUPPLY_CAP     (pass)
```

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    }
```suggestion
        assertEq(ReserveConfiguration.MAX_VALID_SUPPLY_CAP, 68_719_476_735);
```

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
        ( ,,, uint48 lastUpdateBlock, uint48 lastIncreaseTime ) = capAutomator.supplyCapConfigs(asset);
```

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
        ( ,,, uint48 postExecUpdateBlock, uint48 postExecIncreaseTime ) = capAutomator.supplyCapConfigs(asset);
```

(applies to all)

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    function test_setBorrowCapConfig_invalidCooldown() public {
Same comments apply here for test ordering and boundary conditions.

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
```suggestion
        ( ,,, uint48 lastUpdateBlock, uint48 lastIncreaseTime ) = capAutomator.borrowCapConfigs(asset);
```

I would just do a find and replace on `,,,uint48` to `,,, uint48`

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +
Rm extra line

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +            ,
We should be asserting all values returned from the struct for this

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +            ,
We should be asserting all values from the struct for this

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +    function test_calculateNewCap() public {
`test_calculateNewCap_raiseCap`

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        assertEq(newCap, 1_700);
This is interesting.

If a cap is calculated to be less than the current cap, it can be **reduced** even when we're below the cooldown. If this is intended functionality we should definitely add an inline comment in the contract because that's not immediately obvious.

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.expectCall(address(mockPoolConfigurator), abi.encodeCall(IPoolConfigurator.setSupplyCap, (asset, uint256(7_400))), 1);
I think its worth adding a comment here that `(scaledTotalSupply + accruedToTreasury) * liquidityIndex + gap = (5700 + 50) * 1.2 + 500 = 6900 + 500 = 7400`

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.warp(100);
Lets set these values to be different so we know that the right values are being set in the right places

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.roll(100);
Yeah I guess that comment got put out of place

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.warp(100);
Lets change all of these to 100 and 200, can't tell which is being set to which currently

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator.execBorrow(asset), 4_400);
Lets add a quick comment to explain that this is 4_400 because the debt was at 3_900 + 500

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.expectCall(address(mockPoolConfigurator), abi.encodeCall(IPoolConfigurator.setSupplyCap, (asset, uint256(7_300))), 1);
Comments explaining numbers

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        emit UpdateSupplyCap(asset, 7_000, 7_300);
`// 6900 + 400`

2023-12-12 22:11 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        emit UpdateBorrowCap(asset, 4_000, 4_200);
`// 3900 + 300`

2023-12-12 22:11 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     *  @return max              Maximum allowed supply cap
```suggestion
     *  @param  asset            The address of the asset which config is going to be returned
```

2023-12-12 22:11 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     *  @return max              Maximum allowed supply cap
Still need to add periods to all descriptions

2023-12-12 22:11 UTC, lucas-manuel commented on src/interfaces/ICapAutomator.sol
> +     *  @return max              Maximum allowed borrow cap
```suggestion
     *  @param  asset            The address of the asset which config is going to be returned
```

2023-12-12 22:15 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        vm.roll(100);
This got messed up with the lines somehow, meant this line:

`// (aToken.totalSupply + accruedToTreasury) * liquidityIndex = 6_900e6` All comments like this should be above not below

2023-12-12 22:20 UTC, lucas-manuel commented on src/CapAutomator.sol
> +
```suggestion
        uint256 currentSupplyCap = reserveData.configuration.getSupplyCap();

        uint256 currentSupply = (
                IScaledBalanceToken(reserveData.aTokenAddress).scaledTotalSupply()
                + uint256(reserveData.accruedToTreasury)
            ).rayMul(reserveData.liquidityIndex)
            / (10 ** ERC20(reserveData.aTokenAddress).decimals());
```

2023-12-12 22:21 UTC, lucas-manuel commented on src/CapAutomator.sol
> +            / 10 ** ERC20(reserveData.variableDebtTokenAddress).decimals();
```suggestion
        uint256 currentBorrowCap = reserveData.configuration.getBorrowCap();

        // `stableDebt` is not in use and is always 0
        uint256 currentBorrow =
            ERC20(reserveData.variableDebtTokenAddress).totalSupply()
            / 10 ** ERC20(reserveData.variableDebtTokenAddress).decimals();
```

2023-12-13 08:52 UTC, barrutko commented on test/CapAutomator.t.sol
> +        assertEq(newCap, 1_700);
Yes, this is an intended behaviour. I'm adding a comment.

2023-12-14 12:37 UTC, lucas-manuel commented
Still need to do a find and replace for `,,,uint48 => ,,, uint48`

2023-12-14 12:46 UTC, lucas-manuel requested changes

2023-12-14 12:46 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        assertEq(capAutomator.owner(), owner);
Don't need state assertions here cause its a failure test

2023-12-14 12:46 UTC, lucas-manuel commented on test/CapAutomator.t.sol
> +        assertEq(lastIncreaseTime, 0);
For both of these tests lets update the caps so that these values are non zero so we can see them be set to zero

2023-12-14 13:06 UTC, lucas-manuel approved these changes

2023-12-14 16:30 UTC, hexonaut approved these changes
LGTM

2023-12-15 13:19 UTC, merged