fix: add audit fixes
marsfoundation/sparklend-cap-automator pull request #4
Opened 2024-02-12 21:18 UTC by barrutko

2024-02-12 22:16 UTC, lucas-manuel approved these changes, later dismissed

2024-02-13 12:17 UTC, hexonaut requested changes
Minor changes. Code looks good.

2024-02-13 12:17 UTC, hexonaut commented on test/CapAutomator.t.sol
> +
Extra newline.

2024-02-13 12:17 UTC, hexonaut commented on test/CapAutomator.t.sol
>      function test_RemoveSupplyCapConfig() public {
`Remove` -> `remove`

2024-02-13 12:17 UTC, hexonaut commented on test/CapAutomator.t.sol
>      function test_RemoveBorrowCapConfig() public {
`Remove` -> `remove`

2024-02-13 12:17 UTC, hexonaut commented on test/CapAutomator.t.sol
>      function test_UpdateSupplyCap() public {
`Update` -> `update`. And check other places this may be incorrectly capitalized on the first word.

2024-02-13 17:16 UTC, hexonaut approved these changes

2024-02-13 17:54 UTC, lucas-manuel approved these changes

2024-02-13 17:59 UTC, merged